branches:
  only:
    - hexo

language: node_js
node_js:
  - lts/*
cache:
  directories:
    - node_modules

install:
  - npm install
script:
  - git config --global user.name ${UID}
  - git config --global user.email ${EMAIL}
  - git config --global credential.username ${TOKEN}
  - npm run deploy
