branches:
  only: 
    - hexo

env:
  global:
    - GIT_URI: github.com/TechQuery/TechQuery.github.io

language: node_js
node_js: 
  - lts/*
cache:
  directories:
    - node_modules

install:
  - npm install
before_script:
  - git clone --branch master https://${TOKEN}@${GIT_URI}.git public
  - cd public
script:
  - npm run build
  - git add .
  - git config user.name "TechQuery"
  - git config user.email "shiy2008@gmail.com"
  - git commit -m ":memo:\ Update HTML by Travis CI"
  - git push --quiet
