branches:
  only: 
    - hexo

env:
  global:
    - GIT_URI: github.com/TechQuery/TechQuery.github.io

language: node_js
node_js: 
  - lts/*
cache:
  directories:
    - node_modules

install:
  - npm install
script:
  - npm run build
after_script:
  - cd public
  - echo tech-query.me > CNAME
  - git init
  - git config user.name "TechQuery"
  - git config user.email "shiy2008@gmail.com"
  - git add .
  - git commit -m ":memo:\ Update HTML by Travis CI"
  - git push --force --quiet https://${TOKEN}@${GIT_URI}.git master:master