# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: TechQuery
subtitle: Web & JavaScript
description: TechQuery, a Web & JavaScript full-stack developer
keywords: TechQuery website Web JavaScript full-stack developer development coder programmer
author: TechQuery
language: zh-CN
timezone: Asia/Chongqing

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://tech-query.me
root: /
permalink: :title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: false

prism_plugin:
  mode: preprocess # realtime/preprocess
  theme: atom-dark
  line_number: false # default false
  custom_css:

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 9
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 6
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: matery

search:
  path: search.xml
  field: post

permalink_pinyin:
  enable: true

feed:
  type: atom
  path: atom.xml
  limit: 20
  hub:
  content:
  content_limit: 140
  content_limit_delim: ' '
  order_by: -date

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: https://github.com/TechQuery/TechQuery.github.io
  branch: master

auto_category:
  enable: true

# PWA plugin
pwa:
  manifest:
    path: /manifest.json
    body:
      name: TechQuery
      short_name: TechQuery
      start_url: https://tech-query.me/
      description: Personal Web site of TechQuery focused on Web & JavaScript full-stack development
      scope: /
      display: standalone
      orientation: any
      lang: zh-CN
      dir: ltr
      theme_color: rgba(0,0,0,0.5)
      background_color: transparent
      icons:
        - src: /image/WebCell-0.png
          type: image/png
          sizes: 300x300
  serviceWorker:
    path: /sw.js
    preload:
      urls:
        - /
      posts: 5
    opts:
      networkTimeoutSeconds: 5
    routes:
      - pattern: !!js/regexp /\//
        strategy: networkFirst
      - pattern: !!js/regexp /.*\.(css|js|jpg|jpeg|png|gif|webp)$/
        strategy: cacheFirst
      - pattern: !!js/regexp /google.*\.com/
        strategy: networkOnly
      - pattern: !!js/regexp /disqus.*\.com/
        strategy: networkOnly
      - pattern: !!js/regexp /cnzz\.com/
        strategy: networkOnly
  priority: 5
