name: CI & CD
on:
  push:
    branches:
      - hexo
jobs:
  Build-and-Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm
      - name: Install & Build
        run: npm i  &&  npm run build

      - name: Deploy Web-site
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./public
          cname: tech-query.me
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: master
          force_orphan: true
