name: CI & CD
on:
  push:
    branches:
      - hexo
jobs:
  Build-and-Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm
      - name: Install Dependencies
        run: pnpm i --frozen-lockfile

      - name: Build Production
        run: pnpm build

      - name: Deploy Web-site
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./public
          cname: tech-query.me
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: master
          force_orphan: true
